In [2]:
import numpy as np
P = np.array([[[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

        [[0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0]],

        [[0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0.2],
        [0, 0, 0, 0, 0.2],
        [0, 0, 0, 0, 0.6]]])
print(P)

[[[1.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  1.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]]

 [[0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]]

 [[0.  0.  1.  0.  0. ]
  [0.  0.  0.  1.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  1.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]]

 [[0.  0.  1.  0.  0. ]
  [0.  0.  0.  1.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0. ]
  [0.  1.  0.  0.  0. ]]

 [[0.  0.  0.  0.  0. ]
  [0.  0.  0.  1.  0. ]
  [0.  0.  0.  0.  0.2]
  [0.  0.  0.  0.  0.2]
  [0.  0.  0.  0.  0.6]]]


In [3]:
R = np.array([
    [0, 10, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, -2, -10, 4, 0],
    [0, -2, -10, 8, 0],
    [0, 0, 0, 10, 1]
])
print(R)

[[  0  10   0   0   0]
 [  0   0   0   0   0]
 [  0  -2 -10   4   0]
 [  0  -2 -10   8   0]
 [  0   0   0  10   1]]


In [4]:
Q = np.array([
    [14.28125, 14.28125, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 4.5625, 4.28125, 4, 0],
    [0, 7.40625, 4.28125, 8, 0],
    [0, 0, 0, 10, 8.8125]
])
print(Q)

[[14.28125 14.28125  0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.     ]
 [ 0.       4.5625   4.28125  4.       0.     ]
 [ 0.       7.40625  4.28125  8.       0.     ]
 [ 0.       0.       0.      10.       8.8125 ]]


In [5]:
pi = np.array([[0.5,0.5,0,0,0],
         [0,0,0,0,0],
         [0,0.333,0.333,0.333,0],
         [0,0.333,0.333,0.333,0],
         [0,0,0,0.5,0.5]])
x=np.array([1,1,1,1,1])
V_pi=np.dot(np.multiply(pi,Q),x)
print(V_pi)

[14.28125     0.          4.27696875  6.5559375   9.40625   ]


In [6]:
V_pi_P=np.dot(V_pi,P)
print(V_pi_P)

[[14.28125     4.27696875  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          6.5559375  14.28125     0.          0.        ]
 [ 0.          9.40625    14.28125     0.          0.        ]
 [ 0.          0.          0.          0.          7.81033125]]


In [8]:
Q_pi=(R+V_pi_P)
print(Q_pi)

[[14.28125    14.27696875  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          4.5559375   4.28125     4.          0.        ]
 [ 0.          7.40625     4.28125     8.          0.        ]
 [ 0.          0.          0.         10.          8.81033125]]
